In [685]:
import igraph as ig
import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy

In [686]:
def draw_graph(g):
    fig, ax = plt.subplots(figsize=(3, 3))
    ig.plot(
        g,
        target=ax,
        # layout = petersen.layout("sphere"),
        vertex_size=30,
        vertex_label=range(10),
        vertex_color="lightblue",
        edge_width=[3],
        edge_color=["black"]
    )

In [687]:
g = ig.Graph([(0, 1), (0, 2)])

In [688]:
# print(g.vcount())
# draw_graph(g)
# g.contract_vertices([0, 1, 1])
# print(g.vcount())
# g.simplify()
# print(g.vcount())
# draw_graph(g)

In [689]:
def collapse_edge_mapping(g, e):
  for e in g.es: 
    mapping = np.array(range(g.vcount()))
    mapping[e.target] = e.source
    print(mapping)
    return mapping

In [690]:
def collapse_edge(g, e):
  v1 = min(e.source, e.target)
  v2 = max(e.source, e.target)
  l = []
  for (x, y) in g.get_edgelist():
    v3 = min(x, y)
    v4 = max(x, y)
    if v3 == v2:
      v3 = v1
    if v4 == v2:
      v4 = v1
    l.append((v3, v4))
  return (ig.Graph(n = g.vcount() - 1, edges = l)).simplify()

In [691]:
# function: input graph and computes the number of minimum spanning trees recursively
def MST(g):
    n = 0
    if g.ecount() == 0:
        if g.vcount() == 1:
            # print("found MST")
            n = 1
        else:
            # print("found no MST")
            n = 0
    else:
        for e in g.es:
            g1 = deepcopy(g)
            # print("delete edge", e.tuple, "from", g1.get_edgelist(), "with vcount", g1.vcount())
            g1.delete_edges(e.tuple)
            n1 = MST(g1)

            g2 = deepcopy(g)
            print("collapse edge", e.tuple, "from", g2.get_edgelist(), "with vcount", g2.vcount())
            # g2 = collapse_edge(g2, e)
            mapping = collapse_edge_mapping(g2, e)
            g2.contract_vertices(mapping)
            g2.simplify()
            print("after collapsing", e.tuple, "to", g2.get_edgelist(), "with vcount", g2.vcount())
            # g2.delete_vertices([e.target])
            n2 = MST(g2)

            n += n1 + n2
        
    # draw_graph(g)
    # print("MST(", g.get_edgelist(), g.vcount(), ") =", n)
    return n


In [692]:
# call the function
MST(g)

collapse edge (0, 2) from [(0, 2)] with vcount 3
[0 1 0]
after collapsing (0, 2) to [] with vcount 2
collapse edge (0, 1) from [(0, 1), (0, 2)] with vcount 3
[0 0 2]
after collapsing (0, 1) to [(0, 2)] with vcount 3
collapse edge (0, 2) from [(0, 2)] with vcount 3
[0 1 0]
after collapsing (0, 2) to [] with vcount 2
collapse edge (0, 1) from [(0, 1)] with vcount 3
[0 0 2]
after collapsing (0, 1) to [] with vcount 3
collapse edge (0, 2) from [(0, 1), (0, 2)] with vcount 3
[0 0 2]
after collapsing (0, 2) to [(0, 2)] with vcount 3
collapse edge (0, 2) from [(0, 2)] with vcount 3
[0 1 0]
after collapsing (0, 2) to [] with vcount 2


0

In [693]:
# def contract_and_simplify(g, e):
#     g.contract_vertices([e.source, e.target])
#     g.simplify()
#     return g

